// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(apiKey: "AIzaSyBzv4mFC5ToEPKWLqlKT4OEXOmrNEoroG4",
  authDomain: "interview-2e1ee.firebaseapp.com",
  projectId: "interview-2e1ee",
  storageBucket: "interview-2e1ee.appspot.com",
  messagingSenderId: "976124290334",
  appId: "1:976124290334:web:fe1a79e7547366b741550f",
  measurementId: "G-8XBME8G2S9"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjp3O1CSsdxbRNtrwXjiLlbsAbjacn9WI',
    appId: '1:976124290334:android:1ddc9f3747c4186641550f',
    messagingSenderId: '976124290334',
    projectId: 'interview-2e1ee',
    storageBucket: 'interview-2e1ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0z38tYFBQ3Y0X-HO3ox8V5eArGTXtDo',
    appId: '1:976124290334:ios:d1b1755285800f3c41550f',
    messagingSenderId: '976124290334',
    projectId: 'interview-2e1ee',
    storageBucket: 'interview-2e1ee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG0z38tYFBQ3Y0X-HO3ox8V5eArGTXtDo',
    appId: '1:976124290334:ios:d1b1755285800f3c41550f',
    messagingSenderId: '976124290334',
    projectId: 'interview-2e1ee',
    storageBucket: 'interview-2e1ee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
   apiKey: "AIzaSyBzv4mFC5ToEPKWLqlKT4OEXOmrNEoroG4",
  authDomain: "interview-2e1ee.firebaseapp.com",
  projectId: "interview-2e1ee",
  storageBucket: "interview-2e1ee.appspot.com",
  messagingSenderId: "976124290334",
  appId: "1:976124290334:web:fe1a79e7547366b741550f",
  measurementId: "G-8XBME8G2S9"
  );
}
